% Generate neuroSEE ROI files & call FISSA python code
tic
%% Load module folders and define data directory
test = 0;       % set to 1 if testing, this will use one of smaller files in ../test
data_locn = load_neuroSEEmodules(test);
                
file = '20190406_20_33_01';
reference = [];

%% Input folders & files

% green channel tif file
tifdir  = [data_locn 'Data/' file(1:8) '/Processed/' file '/mcorr_normcorre/registered_to_20190406_20_27_07/CaImAn/FISSA/'];
tiffile  = [data_locn 'Data/' file(1:8) '/Processed/' file '/mcorr_normcorre/registered_to_20190406_20_27_07/' file '_2P_XYT_green_mcorr_ref20190406_20_27_07.tif'];

% name of mask generated by NeuroSEE from which ROIs will be generated
roifile = [data_locn 'Data/' file(1:8) '/Processed/' file '/mcorr_normcorre/registered_to_20190406_20_27_07/CaImAn/' file(1:8) '_masks']; 

% directory to store ImageJ ROI files to
roidir  = [data_locn 'Data/' file(1:8) '/Processed/' file '/mcorr_normcorre/registered_to_20190406_20_27_07/CaImAn/FISSA/rois']; 

% output directory to save FISSA outputs to 
outdir  = [data_locn 'Data/' file(1:8) '/Processed/' file '/mcorr_normcorre/registered_to_20190406_20_27_07/CaImAn/FISSA/out']; 

% load mask 
load( fullfile( roifile) );

% if roi directory doesn't exist, create it
if ~exist( roidir, 'dir' )
   mkdir( roidir );
end
% if output directory doesn't exist, create it
if ~exist( outdir, 'dir' )
   mkdir( outdir );
end


%% Generate ROI files
% roi's in masks, with format szx x szy x cell (e.g. 512 x 512 x 101)

[szX, szY, N] = size(masks); % number of ROIs
emptyImg = zeros( szX, szY );
roizip   = fullfile( tifdir, 'rois.zip' );
roifiles = cell(N,1); % list of roi files
for i=1:N
   mask  = masks(:,:,i); 
   % grow mask by 1 pixel to include entire cell within the mask
   elmt  = strel('disk', 1); 
   mask  = imdilate( mask, elmt );
   fname = sprintf('%d.roi', i); % filename for current mask
   
   % generate ROI files by manually writing binary files 
   [err, roi_fname] = exportMask2ROI( roidir, fname, mask );   
   roifiles{i} = roi_fname;
end

% Generate zip file of all ROIs - note that doing this manually in Finder
% (assuming a mac imagecomputer) generated a zip file that failed when being
% input to the fissa code, but I've no idea why?!
zip( roizip, roifiles );

%% Run FISSA
% Now we need to run fissa using python
pyfun = [pwd '/runFISSA.py' ' ' tiffile ' ' roizip ' ' outdir];
python_executable = '/Users/mgo/anaconda3/envs/neuroSEE/bin/python';
pystr =  [python_executable ' ' pyfun];
% [status, pyout] = 
system( pystr )
toc



