function neuroSEE_slackNotify( slacktext )
    SendSlackNotification('https://hooks.slack.com/services/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', ...
       slacktext, '@m.go', ...
       [], [], [], []);    
end